drop table if exists list_domain CASCADE; 
drop table if exists to_do_domain CASCADE; 
create table list_domain (id bigint generated by default as identity, name varchar(255), primary key (id));
create table to_do_domain (id bigint generated by default as identity, completion varchar(255), date_created varchar(255), deadline_date varchar(255), description varchar(255), my_list_id bigint, primary key (id));
alter table to_do_domain add constraint FK25iviyx8kfc7tvyrusifhjpbt foreign key (my_list_id) references list_domain on delete cascade;